name = "JuliaPackageDemo"
uuid = "436bb24b-83cb-42ba-9913-7d4dc472a996"
authors = ["Louis Kaplan <j.kiszle@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
MittagLeffler = "9c257583-4f8f-53fd-abd9-c69d5080dd54"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.4.1"